languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "lois.postu.la"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

[params.author]
  name = "Loïs Postula"
  image = "img/author.png"
  headline = "Yes, I'm a DevOps Engineer. No, I'm Not a Bot (Probably)."
  bio = "Yes, I'm a DevOps Engineer. No, I'm Not a Bot (Probably)."
  links = [
    { email = "mailto:lois@postu.la" },
    { link = "https://lois.postu.la/" },
    { github = "https://github.com/loispostula" },
    { key = "https://lois.postu.la/key/loispostula.asc" }
   ]
